// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using Newtonsoft.Json.Linq;

namespace WTM.ApiClient.Models
{
    public partial class UserSummary
    {
        private string avatarUrl;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AvatarUrl
        {
            get { return this.avatarUrl; }
            set { this.avatarUrl = value; }
        }
        
        private string profilUrl;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ProfilUrl
        {
            get { return this.profilUrl; }
            set { this.profilUrl = value; }
        }
        
        private string rank;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Rank
        {
            get { return this.rank; }
            set { this.rank = value; }
        }
        
        private string username;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Username
        {
            get { return this.username; }
            set { this.username = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IUserSummary class.
        /// </summary>
        public UserSummary()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken avatarUrlValue = inputObject["AvatarUrl"];
                if (avatarUrlValue != null && avatarUrlValue.Type != JTokenType.Null)
                {
                    this.AvatarUrl = ((string)avatarUrlValue);
                }
                JToken profilUrlValue = inputObject["ProfilUrl"];
                if (profilUrlValue != null && profilUrlValue.Type != JTokenType.Null)
                {
                    this.ProfilUrl = ((string)profilUrlValue);
                }
                JToken rankValue = inputObject["Rank"];
                if (rankValue != null && rankValue.Type != JTokenType.Null)
                {
                    this.Rank = ((string)rankValue);
                }
                JToken usernameValue = inputObject["Username"];
                if (usernameValue != null && usernameValue.Type != JTokenType.Null)
                {
                    this.Username = ((string)usernameValue);
                }
            }
        }
    }
}
