// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using Newtonsoft.Json.Linq;

namespace WTM.ApiClient.Models
{
    public partial class MovieSummary
    {
        private string id;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Id
        {
            get { return this.id; }
            set { this.id = value; }
        }
        
        private string image;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Image
        {
            get { return this.image; }
            set { this.image = value; }
        }
        
        private string title;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Title
        {
            get { return this.title; }
            set { this.title = value; }
        }
        
        private int? year;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Year
        {
            get { return this.year; }
            set { this.year = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the MovieSummary class.
        /// </summary>
        public MovieSummary()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the MovieSummary class with required
        /// arguments.
        /// </summary>
        public MovieSummary(string id, string title, string image)
            : this()
        {
            if (id == null)
            {
                throw new ArgumentNullException("id");
            }
            if (title == null)
            {
                throw new ArgumentNullException("title");
            }
            if (image == null)
            {
                throw new ArgumentNullException("image");
            }
            this.Id = id;
            this.Title = title;
            this.Image = image;
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type MovieSummary
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Id == null)
            {
                throw new ArgumentNullException("Id");
            }
            if (this.Image == null)
            {
                throw new ArgumentNullException("Image");
            }
            if (this.Title == null)
            {
                throw new ArgumentNullException("Title");
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id;
            }
            if (this.Image != null)
            {
                outputObject["Image"] = this.Image;
            }
            if (this.Title != null)
            {
                outputObject["Title"] = this.Title;
            }
            if (this.Year != null)
            {
                outputObject["Year"] = this.Year.Value;
            }
            return outputObject;
        }
    }
}
