// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace WTM.ApiClient.Models
{
    public partial class ShotSolutionRequest
    {
        private string token;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Token
        {
            get { return this.token; }
            set { this.token = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ShotSolutionRequest class.
        /// </summary>
        public ShotSolutionRequest()
        {
        }
    }
}
