// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using Newtonsoft.Json.Linq;

namespace WTM.ApiClient.Models
{
    public partial class UserResponse
    {
        private User user;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public User User
        {
            get { return this.user; }
            set { this.user = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the UserResponse class.
        /// </summary>
        public UserResponse()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken userValue = inputObject["User"];
                if (userValue != null && userValue.Type != JTokenType.Null)
                {
                    User user = new User();
                    user.DeserializeJson(userValue);
                    this.User = user;
                }
            }
        }
    }
}
