// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace WTM.ApiClientGenerated.Models
{
    public partial class GuessSolutionRequest
    {
        private string _title;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        private string _token;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Token
        {
            get { return this._token; }
            set { this._token = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the GuessSolutionRequest class.
        /// </summary>
        public GuessSolutionRequest()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the GuessSolutionRequest class with
        /// required arguments.
        /// </summary>
        public GuessSolutionRequest(string title)
            : this()
        {
            if (title == null)
            {
                throw new ArgumentNullException("title");
            }
            this.Title = title;
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type GuessSolutionRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Title == null)
            {
                throw new ArgumentNullException("Title");
            }
            if (this.Title != null)
            {
                outputObject["Title"] = this.Title;
            }
            if (this.Token != null)
            {
                outputObject["Token"] = this.Token;
            }
            return outputObject;
        }
    }
}
