// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace WTM.ApiClientGenerated.Models
{
    public partial class IShotSummary
    {
        private int _id;
        
        /// <summary>
        /// Required.
        /// </summary>
        public int Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _status;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Status
        {
            get { return this._status; }
            set { this._status = value; }
        }
        
        private string _thumb;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Thumb
        {
            get { return this._thumb; }
            set { this._thumb = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IShotSummary class.
        /// </summary>
        public IShotSummary()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the IShotSummary class with required
        /// arguments.
        /// </summary>
        public IShotSummary(int id, string thumb, string status)
            : this()
        {
            if (thumb == null)
            {
                throw new ArgumentNullException("thumb");
            }
            if (status == null)
            {
                throw new ArgumentNullException("status");
            }
            this.Id = id;
            this.Thumb = thumb;
            this.Status = status;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken statusValue = inputObject["Status"];
                if (statusValue != null && statusValue.Type != JTokenType.Null)
                {
                    this.Status = ((string)statusValue);
                }
                JToken thumbValue = inputObject["Thumb"];
                if (thumbValue != null && thumbValue.Type != JTokenType.Null)
                {
                    this.Thumb = ((string)thumbValue);
                }
            }
        }
    }
}
