// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;
using WTM.ApiClientGenerated.Models;

namespace WTM.ApiClientGenerated.Models
{
    public partial class MovieSearchTagRequest
    {
        private IList<MovieSummary> _items;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<MovieSummary> Items
        {
            get { return this._items; }
            set { this._items = value; }
        }
        
        private int? _limit;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Limit
        {
            get { return this._limit; }
            set { this._limit = value; }
        }
        
        private int? _start;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Start
        {
            get { return this._start; }
            set { this._start = value; }
        }
        
        private string _token;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Token
        {
            get { return this._token; }
            set { this._token = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the MovieSearchTagRequest class.
        /// </summary>
        public MovieSearchTagRequest()
        {
            this.Items = new LazyList<MovieSummary>();
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type MovieSearchTagRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            JArray itemsSequence = null;
            if (this.Items != null)
            {
                if (this.Items is ILazyCollection<MovieSummary> == false || ((ILazyCollection<MovieSummary>)this.Items).IsInitialized)
                {
                    itemsSequence = new JArray();
                    outputObject["Items"] = itemsSequence;
                    foreach (MovieSummary itemsItem in this.Items)
                    {
                        if (itemsItem != null)
                        {
                            itemsSequence.Add(itemsItem.SerializeJson(null));
                        }
                    }
                }
            }
            if (this.Limit != null)
            {
                outputObject["Limit"] = this.Limit.Value;
            }
            if (this.Start != null)
            {
                outputObject["Start"] = this.Start.Value;
            }
            if (this.Token != null)
            {
                outputObject["Token"] = this.Token;
            }
            return outputObject;
        }
    }
}
