// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;
using WTM.ApiClientGenerated.Models;

namespace WTM.ApiClientGenerated.Models
{
    public partial class ShotGuessTitleResponse
    {
        private IShotMovieSolution _shotMovieSolution;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IShotMovieSolution ShotMovieSolution
        {
            get { return this._shotMovieSolution; }
            set { this._shotMovieSolution = value; }
        }
        
        private bool _success;
        
        /// <summary>
        /// Required.
        /// </summary>
        public bool Success
        {
            get { return this._success; }
            set { this._success = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ShotGuessTitleResponse class.
        /// </summary>
        public ShotGuessTitleResponse()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the ShotGuessTitleResponse class with
        /// required arguments.
        /// </summary>
        public ShotGuessTitleResponse(bool success)
            : this()
        {
            this.Success = success;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken shotMovieSolutionValue = inputObject["ShotMovieSolution"];
                if (shotMovieSolutionValue != null && shotMovieSolutionValue.Type != JTokenType.Null)
                {
                    IShotMovieSolution iShotMovieSolution = new IShotMovieSolution();
                    iShotMovieSolution.DeserializeJson(shotMovieSolutionValue);
                    this.ShotMovieSolution = iShotMovieSolution;
                }
                JToken successValue = inputObject["Success"];
                if (successValue != null && successValue.Type != JTokenType.Null)
                {
                    this.Success = ((bool)successValue);
                }
            }
        }
    }
}
