// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace WTM.ApiClientGenerated.Models
{
    public partial class ShotNewSubmissionsRequest
    {
        private int? _limit;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Limit
        {
            get { return this._limit; }
            set { this._limit = value; }
        }
        
        private int? _start;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Start
        {
            get { return this._start; }
            set { this._start = value; }
        }
        
        private string _token;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Token
        {
            get { return this._token; }
            set { this._token = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ShotNewSubmissionsRequest class.
        /// </summary>
        public ShotNewSubmissionsRequest()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the ShotNewSubmissionsRequest class
        /// with required arguments.
        /// </summary>
        public ShotNewSubmissionsRequest(string token)
            : this()
        {
            if (token == null)
            {
                throw new ArgumentNullException("token");
            }
            this.Token = token;
        }
    }
}
