// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;
using WTM.ApiClientGenerated.Models;

namespace WTM.ApiClientGenerated.Models
{
    public partial class ShotSolutionResponse
    {
        private bool _available;
        
        /// <summary>
        /// Required.
        /// </summary>
        public bool Available
        {
            get { return this._available; }
            set { this._available = value; }
        }
        
        private IShotMovieSolution _shotMovieSolution;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IShotMovieSolution ShotMovieSolution
        {
            get { return this._shotMovieSolution; }
            set { this._shotMovieSolution = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ShotSolutionResponse class.
        /// </summary>
        public ShotSolutionResponse()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the ShotSolutionResponse class with
        /// required arguments.
        /// </summary>
        public ShotSolutionResponse(bool available)
            : this()
        {
            this.Available = available;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken availableValue = inputObject["Available"];
                if (availableValue != null && availableValue.Type != JTokenType.Null)
                {
                    this.Available = ((bool)availableValue);
                }
                JToken shotMovieSolutionValue = inputObject["ShotMovieSolution"];
                if (shotMovieSolutionValue != null && shotMovieSolutionValue.Type != JTokenType.Null)
                {
                    IShotMovieSolution iShotMovieSolution = new IShotMovieSolution();
                    iShotMovieSolution.DeserializeJson(shotMovieSolutionValue);
                    this.ShotMovieSolution = iShotMovieSolution;
                }
            }
        }
    }
}
