// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace WTM.ApiClientGenerated.Models
{
    public partial class ShotSearchRequest
    {
        private int? _limit;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Limit
        {
            get { return this._limit; }
            set { this._limit = value; }
        }
        
        private int? _start;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Start
        {
            get { return this._start; }
            set { this._start = value; }
        }
        
        private string _tag;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Tag
        {
            get { return this._tag; }
            set { this._tag = value; }
        }
        
        private string _token;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Token
        {
            get { return this._token; }
            set { this._token = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ShotSearchRequest class.
        /// </summary>
        public ShotSearchRequest()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the ShotSearchRequest class with
        /// required arguments.
        /// </summary>
        public ShotSearchRequest(string tag)
            : this()
        {
            if (tag == null)
            {
                throw new ArgumentNullException("tag");
            }
            this.Tag = tag;
        }
    }
}
