// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace WTM.ApiClientGenerated.Models
{
    public partial class ShotRandomRequest
    {
        private string _token;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Token
        {
            get { return this._token; }
            set { this._token = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ShotRandomRequest class.
        /// </summary>
        public ShotRandomRequest()
        {
        }
    }
}
