// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace WTM.RestApi.Client.Models
{
    public partial class FavouritesDeleteRequest
    {
        private string _token;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Token
        {
            get { return this._token; }
            set { this._token = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the FavouritesDeleteRequest class.
        /// </summary>
        public FavouritesDeleteRequest()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the FavouritesDeleteRequest class
        /// with required arguments.
        /// </summary>
        public FavouritesDeleteRequest(string token)
            : this()
        {
            if (token == null)
            {
                throw new ArgumentNullException("token");
            }
            this.Token = token;
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type FavouritesDeleteRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Token == null)
            {
                throw new ArgumentNullException("Token");
            }
            if (this.Token != null)
            {
                outputObject["Token"] = this.Token;
            }
            return outputObject;
        }
    }
}
