// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace WTM.RestApi.Client.Models
{
    public partial class IShotArchivesRequest
    {
        private DateTimeOffset? _date;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? Date
        {
            get { return this._date; }
            set { this._date = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IShotArchivesRequest class.
        /// </summary>
        public IShotArchivesRequest()
        {
        }
    }
}
