// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace WTM.RestApi.Client.Models
{
    public partial class IUserSummary
    {
        private string _avatarUrl;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AvatarUrl
        {
            get { return this._avatarUrl; }
            set { this._avatarUrl = value; }
        }
        
        private string _profilUrl;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ProfilUrl
        {
            get { return this._profilUrl; }
            set { this._profilUrl = value; }
        }
        
        private string _rank;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Rank
        {
            get { return this._rank; }
            set { this._rank = value; }
        }
        
        private string _username;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Username
        {
            get { return this._username; }
            set { this._username = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IUserSummary class.
        /// </summary>
        public IUserSummary()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken avatarUrlValue = inputObject["AvatarUrl"];
                if (avatarUrlValue != null && avatarUrlValue.Type != JTokenType.Null)
                {
                    this.AvatarUrl = ((string)avatarUrlValue);
                }
                JToken profilUrlValue = inputObject["ProfilUrl"];
                if (profilUrlValue != null && profilUrlValue.Type != JTokenType.Null)
                {
                    this.ProfilUrl = ((string)profilUrlValue);
                }
                JToken rankValue = inputObject["Rank"];
                if (rankValue != null && rankValue.Type != JTokenType.Null)
                {
                    this.Rank = ((string)rankValue);
                }
                JToken usernameValue = inputObject["Username"];
                if (usernameValue != null && usernameValue.Type != JTokenType.Null)
                {
                    this.Username = ((string)usernameValue);
                }
            }
        }
    }
}
