// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace WTM.RestApi.Client.Models
{
    public partial class IUserSearchRequest
    {
        private string _filter;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Filter
        {
            get { return this._filter; }
            set { this._filter = value; }
        }
        
        private int? _limit;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Limit
        {
            get { return this._limit; }
            set { this._limit = value; }
        }
        
        private int? _start;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Start
        {
            get { return this._start; }
            set { this._start = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IUserSearchRequest class.
        /// </summary>
        public IUserSearchRequest()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the IUserSearchRequest class with
        /// required arguments.
        /// </summary>
        public IUserSearchRequest(string filter)
            : this()
        {
            if (filter == null)
            {
                throw new ArgumentNullException("filter");
            }
            this.Filter = filter;
        }
    }
}
