// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace WTM.RestApi.Client.Models
{
    public partial class MovieSearchTagResponse
    {
        private int? _displayCount;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? DisplayCount
        {
            get { return this._displayCount; }
            set { this._displayCount = value; }
        }
        
        private int? _displayMax;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? DisplayMax
        {
            get { return this._displayMax; }
            set { this._displayMax = value; }
        }
        
        private int? _displayMin;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? DisplayMin
        {
            get { return this._displayMin; }
            set { this._displayMin = value; }
        }
        
        private int? _totalCount;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? TotalCount
        {
            get { return this._totalCount; }
            set { this._totalCount = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the MovieSearchTagResponse class.
        /// </summary>
        public MovieSearchTagResponse()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken displayCountValue = inputObject["DisplayCount"];
                if (displayCountValue != null && displayCountValue.Type != JTokenType.Null)
                {
                    this.DisplayCount = ((int)displayCountValue);
                }
                JToken displayMaxValue = inputObject["DisplayMax"];
                if (displayMaxValue != null && displayMaxValue.Type != JTokenType.Null)
                {
                    this.DisplayMax = ((int)displayMaxValue);
                }
                JToken displayMinValue = inputObject["DisplayMin"];
                if (displayMinValue != null && displayMinValue.Type != JTokenType.Null)
                {
                    this.DisplayMin = ((int)displayMinValue);
                }
                JToken totalCountValue = inputObject["TotalCount"];
                if (totalCountValue != null && totalCountValue.Type != JTokenType.Null)
                {
                    this.TotalCount = ((int)totalCountValue);
                }
            }
        }
    }
}
