// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace WTM.RestApi.Client.Models
{
    public partial class RateRequest
    {
        private int _rate;
        
        /// <summary>
        /// Required.
        /// </summary>
        public int Rate
        {
            get { return this._rate; }
            set { this._rate = value; }
        }
        
        private string _token;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Token
        {
            get { return this._token; }
            set { this._token = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the RateRequest class.
        /// </summary>
        public RateRequest()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the RateRequest class with required
        /// arguments.
        /// </summary>
        public RateRequest(int rate)
            : this()
        {
            this.Rate = rate;
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type RateRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            outputObject["Rate"] = this.Rate;
            if (this.Token != null)
            {
                outputObject["Token"] = this.Token;
            }
            return outputObject;
        }
    }
}
