// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using WTM.RestApi.Client.Models;

namespace WTM.RestApi.Client.Models
{
    public static partial class ShotOverviewResponseCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ShotOverviewResponse> DeserializeJson(JToken inputObject)
        {
            IList<ShotOverviewResponse> deserializedObject = new List<ShotOverviewResponse>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ShotOverviewResponse shotOverviewResponse = new ShotOverviewResponse();
                shotOverviewResponse.DeserializeJson(iListValue);
                deserializedObject.Add(shotOverviewResponse);
            }
            return deserializedObject;
        }
    }
}
