// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace WTM.RestApi.Client.Models
{
    public static partial class StringCollection
    {
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type IList
        /// </returns>
        public static JToken SerializeJson(IList<string> tags, JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            JArray iListSequence = null;
            if (tags != null)
            {
                iListSequence = new JArray();
                outputObject = iListSequence;
                foreach (string iListItem in tags)
                {
                    if (iListItem != null)
                    {
                        iListSequence.Add(iListItem);
                    }
                }
            }
            return outputObject;
        }
    }
}
