// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using WTM.RestApi.Client.Models;

namespace WTM.RestApi.Client
{
    public partial interface IMovie
    {
        /// <param name='tags'>
        /// Required.
        /// </param>
        /// <param name='start'>
        /// Optional.
        /// </param>
        /// <param name='limit'>
        /// Optional.
        /// </param>
        /// <param name='token'>
        /// Optional.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<MovieOverviewResponse>>> FindByTagWithOperationResponseAsync(IList<string> tags, int? start = null, int? limit = null, string token = null, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='name'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<MovieResponse>> GetByNameWithOperationResponseAsync(string name, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
