// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using WTM.RestApi.Client.Models;

namespace WTM.RestApi.Client
{
    public partial interface IMovies
    {
        /// <param name='name'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetWithOperationResponseAsync(string name, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='request'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<MovieSearchTagResponse>> GetByTagWithOperationResponseAsync(MovieSearchTagRequest request, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
