// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using WTM.RestApi.Client.Models;

namespace WTM.RestApi.Client
{
    public partial interface IUserOperations
    {
        /// <param name='username'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<User>> GetWithOperationResponseAsync(string username, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='username'>
        /// Required.
        /// </param>
        /// <param name='password'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<LoginResponse>> LoginWithOperationResponseAsync(string username, string password, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='token'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<LogoutResponse>> LogoutWithOperationResponseAsync(string token, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
